title: Grav
author:
  name: CATA
  email: 'm.ch55000@gmail.com'
metadata:
    description: 'WebdesignGroupe.fr est un site de présentation pour projet d étude sur la ville de Cholet avec des étudiants OC'
    title: 'webdesignGroupe, la nouvelle agence digitale de Cholet'
    robots: 'noindex, nofollow'
    url: 'http://webdesigngroup.fr'



